-- 0102_certification_content_seed.sql
-- Data-only seed, mechanically generated from this session's module1-7-data.js
-- and lab-manual-data.js via lib/certification-content-data/extract script
-- (kept in the scratchpad this session was built in, not re-run per deploy --
-- this file is the durable record of that one extraction). Idempotent: skips
-- if a content_version with this curriculum_version already exists.
do $$
declare
  v_id uuid;
begin
  if not exists (select 1 from certification_content_version where curriculum_version = '2026-10-01' and lab_manual_version = '2026-10-01') then
    insert into certification_content_version (curriculum_version, lab_manual_version, notes)
    values ('2026-10-01', '2026-10-01', 'Seeded from session build data via extract-companion-content.js')
    returning id into v_id;

    insert into certification_curriculum_items (content_version_id, item_key, item_type, module_num, title, sort_order)
    select v_id, x.item_key, x.item_type, x.module_num, x.title, x.sort_order
    from (values
      ('lesson-1.1', 'lesson', 1, 'What AVAIA Is, and Is Not', 0),
      ('lesson-1.2', 'lesson', 1, 'The GIVE Method', 1),
      ('lesson-1.3', 'lesson', 1, 'Awareness -> Understanding -> Agency', 2),
      ('lesson-1.4', 'lesson', 1, 'Host, Guide & Witness: The Table', 3),
      ('lesson-1.5', 'lesson', 1, 'Experience vs. Secondary Loss', 4),
      ('lesson-1.6', 'lesson', 1, 'Governing Principles', 5),
      ('lesson-1.7', 'lesson', 1, 'Authority and Power of the Guide Seat', 6),
      ('lesson-1.8', 'lesson', 1, 'Principles in Tension', 7),
      ('lesson-2.1', 'lesson', 2, 'One Journey, Three Conversations', 8),
      ('lesson-2.2', 'lesson', 2, 'IAP: Awareness -- You Get to Say It', 9),
      ('lesson-2.3', 'lesson', 2, 'CAT: Understanding', 10),
      ('lesson-2.4', 'lesson', 2, 'InnerCompass: Agency', 11),
      ('lesson-2.5', 'lesson', 2, 'Journey Continuity', 12),
      ('lesson-2.6', 'lesson', 2, 'Stay or Move?', 13),
      ('lesson-2.7', 'lesson', 2, 'Completing a Journey', 14),
      ('lesson-2.8', 'lesson', 2, 'Guide Transition During an Active Journey', 15),
      ('lesson-3.1', 'lesson', 3, 'Adaptive vs. Directive Listening', 16),
      ('lesson-3.2', 'lesson', 3, 'Recognition vs. Interpretation', 17),
      ('lesson-3.3', 'lesson', 3, 'Curiosity Without Interrogation', 18),
      ('lesson-3.4', 'lesson', 3, 'Silence', 19),
      ('lesson-3.5', 'lesson', 3, 'Uncertainty', 20),
      ('lesson-3.6', 'lesson', 3, 'Difficult Moments', 21),
      ('lesson-3.7', 'lesson', 3, 'The Guide Is Also at the Table', 22),
      ('lesson-3.8', 'lesson', 3, 'The Guides Own Capacity', 23),
      ('lesson-3.9', 'lesson', 3, 'Guide Mistakes and Repair', 24),
      ('lesson-3.10', 'lesson', 3, 'Working Across Difference and Meaning', 25),
      ('lesson-3.11', 'lesson', 3, 'Guide Self-Disclosure', 26),
      ('lesson-3.12', 'lesson', 3, 'Emotion Is Not an Outcome Measure', 27),
      ('lesson-3.13', 'lesson', 3, 'The Host Does Not Owe the Guide an Outcome', 28),
      ('lesson-3.14', 'lesson', 3, 'Ending a Conversation Well', 29),
      ('lesson-4.1', 'lesson', 4, 'Want -> Should -> Need -> Present Capacity', 30),
      ('lesson-4.2', 'lesson', 4, 'Capacity Is Not Character', 31),
      ('lesson-4.3', 'lesson', 4, 'Mental Capacity', 32),
      ('lesson-4.4', 'lesson', 4, 'Emotional Capacity', 33),
      ('lesson-4.5', 'lesson', 4, 'Physical Capacity', 34),
      ('lesson-4.6', 'lesson', 4, 'Reading Capacity Without Diagnosing It', 35),
      ('lesson-4.7', 'lesson', 4, 'Permission to Stop', 36),
      ('lesson-4.8', 'lesson', 4, 'Same Behavior, Different Reality', 37),
      ('lesson-4.9', 'lesson', 4, 'Capacity Without Performance Pressure', 38),
      ('lesson-5.1', 'lesson', 5, 'Loss of Meaning', 39),
      ('lesson-5.2', 'lesson', 5, 'Loss of Reality', 40),
      ('lesson-5.3', 'lesson', 5, 'Loss of Dreams/Opportunities', 41),
      ('lesson-5.4', 'lesson', 5, 'Loss of Self-Trust', 42),
      ('lesson-5.5', 'lesson', 5, 'Loss of Capacity', 43),
      ('lesson-5.6', 'lesson', 5, 'Loss of Lifes Vision', 44),
      ('lesson-5.7', 'lesson', 5, 'Loss of Connection', 45),
      ('lesson-5.8', 'lesson', 5, 'Loss of Control', 46),
      ('lesson-5.9', 'lesson', 5, 'Loss of Identity', 47),
      ('lesson-5.10', 'lesson', 5, 'Loss of Attachment/Support', 48),
      ('lesson-5.11', 'lesson', 5, 'Masking', 49),
      ('lesson-5.12', 'lesson', 5, 'Stacking', 50),
      ('lesson-5.13', 'lesson', 5, 'Chemistry of Virtue', 51),
      ('lesson-5.14', 'lesson', 5, 'Virtue Formula', 52),
      ('lesson-5.15', 'lesson', 5, 'Virtue Signature', 53),
      ('lesson-5.16', 'lesson', 5, 'Bringing the Recognition Systems Together', 54),
      ('lesson-5.17', 'lesson', 5, 'Recognition Does Not Require Intervention', 55),
      ('lesson-6.1', 'lesson', 6, 'Host Ownership', 56),
      ('lesson-6.2', 'lesson', 6, 'Privacy Architecture', 57),
      ('lesson-6.3', 'lesson', 6, 'Scope', 58),
      ('lesson-6.4', 'lesson', 6, 'Non-Therapy', 59),
      ('lesson-6.5', 'lesson', 6, 'Non-Diagnosis', 60),
      ('lesson-6.6', 'lesson', 6, 'Non-Prescription', 61),
      ('lesson-6.7', 'lesson', 6, 'Capacity to Continue', 62),
      ('lesson-6.8', 'lesson', 6, 'Youth Boundary Fundamentals', 63),
      ('lesson-6.9', 'lesson', 6, 'Safety/Crisis', 64),
      ('lesson-6.10', 'lesson', 6, 'When the Guide Stops Guiding', 65),
      ('lesson-6.11', 'lesson', 6, 'Ongoing Consent and Participation', 66),
      ('lesson-6.12', 'lesson', 6, 'Dual Relationships & Conflicts of Interest', 67),
      ('lesson-6.13', 'lesson', 6, 'Peer Consultation', 68),
      ('lesson-6.14', 'lesson', 6, 'Documentation Without Interpretation', 69),
      ('lesson-6.15', 'lesson', 6, 'Guide Authority and Scope', 70),
      ('lesson-6.16', 'lesson', 6, 'Mandatory Reporting & Legal Obligations', 71),
      ('lesson-6.17', 'lesson', 6, 'Boundary Gate Readiness Review', 72),
      ('lesson-7.1', 'lesson', 7, 'Guide Dashboard', 73),
      ('lesson-7.2', 'lesson', 7, 'Guide Toolkit', 74),
      ('lesson-7.3', 'lesson', 7, 'Preparation', 75),
      ('lesson-7.4', 'lesson', 7, 'Opening a New Host Relationship', 76),
      ('lesson-7.5', 'lesson', 7, 'Journey Operation', 77),
      ('lesson-7.6', 'lesson', 7, 'Privacy in the Actual Interface', 78),
      ('lesson-7.7', 'lesson', 7, 'Workbook & Continuity', 79),
      ('lesson-7.8', 'lesson', 7, 'Library', 80),
      ('lesson-7.9', 'lesson', 7, 'Materials', 81),
      ('lesson-7.10', 'lesson', 7, 'Programs, Experiences & Authorization', 82),
      ('lesson-7.11', 'lesson', 7, 'Operational & Technology Failure', 83),
      ('lesson-7.12', 'lesson', 7, 'Journey Completion in the Platform', 84),
      ('lesson-7.13', 'lesson', 7, 'Guide Transition & Host Continuity: Operational Mechanics', 85),
      ('lab-1', 'practice_lab', null, 'IAP: You Get to Say It', 86),
      ('lab-2', 'practice_lab', null, 'CAT: Landscape, Not Funnel', 87),
      ('lab-3', 'practice_lab', null, 'InnerCompass: Agency Without Advice', 88),
      ('lab-4', 'practice_lab', null, 'Talkative Host', 89),
      ('lab-5', 'practice_lab', null, 'Quiet Host', 90),
      ('lab-6', 'practice_lab', null, 'Uncertain Host', 91),
      ('lab-7', 'practice_lab', null, 'Advice-Seeking Host', 92),
      ('lab-8', 'practice_lab', null, 'Capacity Reached', 93),
      ('lab-9', 'practice_lab', null, 'Strong Emotion', 94),
      ('lab-10', 'practice_lab', null, 'Guide Mistake & Repair', 95),
      ('lab-11', 'practice_lab', null, 'Recognition That Should Not Be Introduced', 96),
      ('lab-12', 'practice_lab', null, 'Scope & Boundary', 97),
      ('lab-13', 'practice_lab', null, 'Guide Reaction & Self-Disclosure', 98),
      ('lab-14', 'practice_lab', null, 'Peer Consultation', 99),
      ('lab-15', 'practice_lab', null, 'Ending Without Forced Resolution', 100)
    ) as x(item_key, item_type, module_num, title, sort_order);
  end if;
end $$;
