-- 0120_coordination_items.sql
--
-- Coordination layer, Phase 1: the first stateful Workbook object.
--
-- The Workbook has been a read-only view over conversations, referrals, kept items and journal
-- entries; AVAIA has had no record of "who is doing what, and what is waiting on whom". This adds
-- exactly one Host-owned table for that, and nothing else.
--
--   coordination_items   one row per thing the Host is coordinating. Every state on it is
--                        Host-selected. Nothing here is inferred, scored or generated by AI, and
--                        there is no capacity field of any kind (Decision 0001 stays separate;
--                        Green/Yellow/Red is not used here).
--
-- Decision 0008 governs: AVAIA may create and preserve a longitudinal record of a Host's expressed
-- understanding, reasoning, choices, questions, and participation in consequential decisions.
-- AVAIA does not independently determine or declare legal capacity or incapacity. `kind =
-- 'decision'` exists now so that record has somewhere to attach later; Phase 1 does not build it.
--
-- Boundaries, enforced in the database and not only in the application:
--   * Host-only. There is no Guide, admin or service policy. (A Guide view is a later phase and will
--     arrive as explicit Host grants, not as a policy on this table.)
--   * Adult account holders only: a self-serve Youth profile (developmental_band set) cannot create
--     or change a row. Account-less participants have no auth user and so cannot own one.
--   * No DELETE policy. A Host closes an item; permanent deletion is deliberately not offered yet.
--   * Pointers only. The table stores ids and one free-text Room label. It never copies any text
--     from IAP, CAT, InnerCompass, a Journal entry or a Room, and it does not touch Room ownership.
--   * The owner, identity and creation time of a row can never change.
--
-- Safe to run more than once.

create table if not exists public.coordination_items (
  id                      uuid primary key default gen_random_uuid(),
  host_id                 uuid not null references auth.users (id) on delete cascade,

  kind                    text not null default 'item' check (kind in ('item', 'decision')),
  title                   text not null check (char_length(btrim(title)) between 1 and 200),
  category                text check (category is null or char_length(category) <= 80),

  -- The Host's own choice, never inferred. Null means the Host has not chosen one.
  delegation_state        text check (delegation_state is null or delegation_state in (
                            'i_own_and_will_do',
                            'i_own_decision_others_carry_out',
                            'someone_else_owns',
                            'belongs_with_professional',
                            'can_wait',
                            'need_help_before_deciding',
                            'no_capacity_now'
                          )),
  assigned_to_name        text check (assigned_to_name is null or char_length(assigned_to_name) <= 200),
  assigned_to_role        text check (assigned_to_role is null or char_length(assigned_to_role) <= 100),
  professional_name       text check (professional_name is null or char_length(professional_name) <= 200),
  professional_role       text check (professional_role is null or char_length(professional_role) <= 100),

  status                  text not null default 'open' check (status in ('open', 'waiting', 'closed')),
  waiting_on              text check (waiting_on is null or waiting_on in ('host', 'guide', 'family_member', 'professional', 'other')),
  waiting_on_note         text check (waiting_on_note is null or char_length(waiting_on_note) <= 500),

  next_action             text check (next_action is null or char_length(next_action) <= 1000),
  due_date                date,

  -- Another item of this same Host that this one relates to (a decision it serves). The composite
  -- foreign key makes it structurally impossible to point at another Host's item.
  related_decision_id     uuid,
  -- Pointers into the Host's own existing records; they never carry any of their text.
  related_conversation_id uuid references public.conversations (id) on delete set null,
  related_referral_id     uuid references public.referrals (id) on delete set null,
  -- A label only. Rooms are read through the facilitating Guide's account, so Phase 1 does not
  -- point at a Room and changes nothing about Room ownership or access.
  related_room_label      text check (related_room_label is null or char_length(related_room_label) <= 200),

  created_at              timestamptz not null default now(),
  updated_at              timestamptz not null default now(),
  closed_at               timestamptz,

  constraint coordination_items_id_host_unique unique (id, host_id),
  constraint coordination_items_related_decision_fk
    foreign key (related_decision_id, host_id) references public.coordination_items (id, host_id),
  constraint coordination_items_not_self_related check (related_decision_id is null or related_decision_id <> id),
  -- Waiting always says what it is waiting on, and nothing else carries a waiting_on.
  constraint coordination_items_waiting_pairing check ((status = 'waiting') = (waiting_on is not null)),
  constraint coordination_items_closed_pairing check ((status = 'closed') = (closed_at is not null))
);

create index if not exists coordination_items_host_status_due_idx
  on public.coordination_items (host_id, status, due_date);
create index if not exists coordination_items_host_created_idx
  on public.coordination_items (host_id, created_at desc);

alter table public.coordination_items enable row level security;

-- Host read: the Host's own rows, and no one else's.
do $$ begin
  create policy "coordination items own read" on public.coordination_items
    for select using (host_id = auth.uid());
exception when duplicate_object then null; end $$;

-- Host write: own rows, an adult account, and pointers that really are the Host's own records
-- (and not a conversation a Guide facilitated for someone else).
do $$ begin
  create policy "coordination items own insert" on public.coordination_items
    for insert with check (
      host_id = auth.uid()
      and not exists (select 1 from public.profiles p where p.id = auth.uid() and p.developmental_band is not null)
      and (
        coordination_items.related_conversation_id is null
        or exists (
          select 1 from public.conversations c
          where c.id = coordination_items.related_conversation_id
            and c.host_id = auth.uid()
            and not exists (select 1 from public.guide_sessions gs where gs.conversation_id = c.id)
        )
      )
      and (
        coordination_items.related_referral_id is null
        or exists (
          select 1 from public.referrals r
          where r.id = coordination_items.related_referral_id
            and r.host_id = auth.uid()
            and (r.conversation_id is null
                 or not exists (select 1 from public.guide_sessions gs where gs.conversation_id = r.conversation_id))
        )
      )
    );
exception when duplicate_object then null; end $$;

do $$ begin
  create policy "coordination items own update" on public.coordination_items
    for update using (host_id = auth.uid())
    with check (
      host_id = auth.uid()
      and not exists (select 1 from public.profiles p where p.id = auth.uid() and p.developmental_band is not null)
      and (
        coordination_items.related_conversation_id is null
        or exists (
          select 1 from public.conversations c
          where c.id = coordination_items.related_conversation_id
            and c.host_id = auth.uid()
            and not exists (select 1 from public.guide_sessions gs where gs.conversation_id = c.id)
        )
      )
      and (
        coordination_items.related_referral_id is null
        or exists (
          select 1 from public.referrals r
          where r.id = coordination_items.related_referral_id
            and r.host_id = auth.uid()
            and (r.conversation_id is null
                 or not exists (select 1 from public.guide_sessions gs where gs.conversation_id = r.conversation_id))
        )
      )
    );
exception when duplicate_object then null; end $$;

-- Deliberately NO delete policy (Phase 1: a Host closes an item).

-- Guard: the owner, identity and creation time never change; updated_at and closed_at are kept
-- by the database so the application cannot get them wrong.
create or replace function public.coordination_items_guard() returns trigger
language plpgsql set search_path = public as $$
begin
  if tg_op = 'UPDATE' then
    if new.id is distinct from old.id
       or new.host_id is distinct from old.host_id
       or new.created_at is distinct from old.created_at then
      raise exception 'A coordination item cannot change its owner, identity or creation time.';
    end if;
  end if;

  new.updated_at := now();

  if new.status = 'closed' then
    if tg_op = 'UPDATE' then
      if old.status = 'closed' and old.closed_at is not null then
        new.closed_at := old.closed_at;
      else
        new.closed_at := now();
      end if;
    else
      new.closed_at := now();
    end if;
  else
    new.closed_at := null;
  end if;

  return new;
end $$;

drop trigger if exists coordination_items_guard on public.coordination_items;
create trigger coordination_items_guard before insert or update on public.coordination_items
  for each row execute function public.coordination_items_guard();

comment on table public.coordination_items is
  'Host-owned coordination items (Workbook). Every state is Host-selected; nothing is inferred, scored or AI-generated, and there is no capacity field. Host-only by design: no Guide, admin or service policy, no DELETE policy, adult accounts only. Pointers only; no conversation, Journal or Room text is copied. Decision 0008.';
comment on column public.coordination_items.delegation_state is
  'Host-selected, never inferred: i_own_and_will_do, i_own_decision_others_carry_out, someone_else_owns, belongs_with_professional, can_wait, need_help_before_deciding, no_capacity_now. Null = not chosen.';
comment on column public.coordination_items.related_room_label is
  'A free-text label only. Phase 1 does not point at a Room and does not alter Room ownership or access.';
comment on column public.coordination_items.kind is
  '''decision'' reserves a place for the Decision and Capacity Continuity record (Decision 0008); Phase 1 does not build it.';
