import { escapeHtml } from "@/lib/resend";

/**
 * Email templates for the three operational agents that send email rather
 * than just writing rows (Agents 6, 7, 10). Every string here is a fixed
 * template -- nothing is generated by a model -- matching the same
 * no-invented-content posture as lib/pink/emails.ts and
 * lib/resend.ts's existing templates.
 */

// ---------------------------------------------------------------------------
// Agent 6 -- AVAIA Host Onboarding. Sent directly to the Host who stalled.
// Deliberately generic and warm: it never references what stage content
// they saw, never quotes anything from their conversation, and never
// implies urgency. "Do not pressure people" is enforced by tone here and by
// the cooldown in lib/ops/host-onboarding.ts.
// ---------------------------------------------------------------------------
const STAGE_LABEL: Record<string, string> = {
  iap_stalled: "your Initial AVAIA Pathway conversation",
  cat_stalled: "your CAT conversation",
  innercompass_stalled: "your InnerCompass conversation",
};

export function hostOnboardingReminderEmailHtml({
  reminderType,
  journeyUrl,
}: {
  reminderType: "iap_stalled" | "cat_eligible_no_start" | "cat_stalled" | "innercompass_stalled";
  journeyUrl: string;
}): string {
  const whatStalled = STAGE_LABEL[reminderType] ?? "your AVAIA conversation";
  return `
    <p>Hi,</p>
    <p>You started ${whatStalled} a little while ago. There's no deadline here, and nothing
    about your progress has been lost -- it's still exactly where you left it, whenever you're
    ready to pick it back up.</p>
    <p><a href="${journeyUrl}">Continue whenever you're ready</a></p>
    <p style="color:#888">If you'd rather not continue right now, you can ignore this --
    we won't send another reminder about this for a while.</p>
  `.trim();
}

// ---------------------------------------------------------------------------
// Agent 7 -- Guide Operations. This does NOT go to the candidate -- it is an
// internal operational notice to Dorian/admin that a specific, mechanical
// waiting condition has been sitting unresolved past the stall threshold.
// It states only identifiers and elapsed time, never an evaluation note,
// a rationale, or any judgment about the candidate's competency -- "do not
// invent certification requirements" means this agent doesn't try to
// evaluate anything either, it only reports elapsed time on facts that
// already exist in guide_certification_payments / guide_candidates.
// ---------------------------------------------------------------------------
export function guideOperationsWaitingNotificationEmailHtml({
  type,
  hostId,
  sinceDays,
  status,
}: {
  type: "candidacy_stalled" | "paid_awaiting_decision";
  hostId: string;
  sinceDays: number;
  status?: string;
}): string {
  const heading =
    type === "paid_awaiting_decision"
      ? "Certification payment awaiting a decision"
      : "Guide candidacy waiting on next step";
  const body =
    type === "paid_awaiting_decision"
      ? `A candidate paid for certification ${sinceDays} day(s) ago and no certification decision has
         been recorded yet.`
      : `A candidacy (status: ${escapeHtml(status ?? "unknown")}) has had no recorded activity in
         ${sinceDays} day(s).`;
  return `
    <h2>${heading}</h2>
    <p>${body}</p>
    <p><strong>Host ID:</strong> ${escapeHtml(hostId)}</p>
    <p style="color:#888">This is a scheduling notice only -- it does not include any evaluation
    notes, application content, or a recommendation. Review the candidate's record directly to
    decide next steps.</p>
  `.trim();
}

// ---------------------------------------------------------------------------
// Agent 10 -- Founder / Operations digest. The exact section order and
// section names are load-bearing -- Dorian specified this format directly:
// WHAT HAPPENED / WHAT IS BEING HANDLED AUTOMATICALLY / WHAT IS WAITING /
// WHAT NEEDS DORIAN / TODAY'S 3-5 PRIORITIES. This function only lays out
// strings the caller (lib/ops/founder-digest.ts) already composed from
// database counts and identifiers -- it never reads message/conversation
// content, and it never invents a priority; if there is nothing for a
// section, the section says so rather than being padded.
// ---------------------------------------------------------------------------
export function founderDigestEmailHtml({
  dateLabel,
  whatHappened,
  automatic,
  waiting,
  needsDorian,
  priorities,
}: {
  dateLabel: string;
  whatHappened: string[];
  automatic: string[];
  waiting: string[];
  needsDorian: string[];
  priorities: string[];
}): string {
  const section = (title: string, lines: string[], emptyLabel: string) => `
    <h2 style="margin-bottom:4px">${escapeHtml(title)}</h2>
    ${
      lines.length
        ? `<ul style="margin-top:4px">${lines.map((l) => `<li>${escapeHtml(l)}</li>`).join("")}</ul>`
        : `<p style="color:#888;margin-top:4px">${escapeHtml(emptyLabel)}</p>`
    }
  `;

  return `
    <h1>AVAIA + Pink Shoelace -- Daily Operating Summary</h1>
    <p style="color:#888">${escapeHtml(dateLabel)}</p>
    ${section("WHAT HAPPENED", whatHappened, "Nothing new since the last summary.")}
    ${section("WHAT IS BEING HANDLED AUTOMATICALLY", automatic, "Nothing currently in automated handling.")}
    ${section("WHAT IS WAITING", waiting, "Nothing waiting.")}
    ${section("WHAT NEEDS DORIAN", needsDorian, "Nothing needs your attention today.")}
    ${section("TODAY'S PRIORITIES", priorities, "No specific priorities surfaced today.")}
  `.trim();
}

// ---------------------------------------------------------------------------
// Certification Companion -- human escalation notice. Sent to
// GUIDE_OPS_NOTIFICATION_EMAIL (same env var Agent 7 already uses) the
// moment the Companion logs a certification_companion_escalations row
// (app/api/certification/companion/route.ts). Like the Agent 7 template
// above, this states identifiers and category only -- never the model's
// reply, never an evaluation, never a recommendation. A crisis category
// reuses the exact resource line already approved in lib/safety.ts
// (CRISIS_RESOURCES.US) rather than writing new crisis wording here.
// ---------------------------------------------------------------------------
const ESCALATION_CATEGORY_LABEL: Record<string, string> = {
  crisis: "Possible crisis content detected",
  waiver_request: "Candidate asked to waive or skip a requirement",
  evaluation_dispute: "Candidate disputed a recorded evaluation",
  judgment_territory: "Candidate asked about a Boundary Gate / Practicum judgment",
  no_confident_match: "Candidate asked a content question the Companion could not confidently answer",
};

export function certificationCompanionEscalationEmailHtml({
  category,
  hostId,
  candidateId,
  note,
}: {
  category: string;
  hostId: string;
  candidateId: string;
  note?: string | null;
}): string {
  const label = ESCALATION_CATEGORY_LABEL[category] ?? "Certification Companion escalation";
  return `
    <h2>${escapeHtml(label)}</h2>
    <p>The AVAIA Certification Companion flagged a conversation that needs a person.</p>
    <p><strong>Host ID:</strong> ${escapeHtml(hostId)}</p>
    <p><strong>Candidate ID:</strong> ${escapeHtml(candidateId)}</p>
    ${note ? `<p><strong>Candidate's message (verbatim, truncated):</strong></p><p style="white-space:pre-wrap">${escapeHtml(note)}</p>` : ""}
    ${
      category === "crisis"
        ? `<p style="color:#8f3b34"><strong>988</strong> (call or text) · <strong>911</strong> for immediate danger · text <strong>HOME</strong> to <strong>741741</strong></p>`
        : ""
    }
    <p style="color:#888">This is a routing notice only -- the Companion did not evaluate, decide,
    or waive anything. Review the conversation directly to decide next steps.</p>
  `.trim();
}

// ---------------------------------------------------------------------------
// Certification Companion -- basic progress-aware check-in, sent directly
// to the candidate (unlike every other template in this file, which is
// internal to Dorian/admin). Deliberately generic and warm, same posture
// as hostOnboardingReminderEmailHtml above: no urgency, no reference to
// what specifically is incomplete beyond the plain fact of inactivity.
// ---------------------------------------------------------------------------
export function certificationCompanionCheckinEmailHtml({ companionUrl }: { companionUrl: string }): string {
  return `
    <p>Hi,</p>
    <p>It's been a little while since you last touched your AVAIA Guide Certification work.
    There's no deadline attached to this note -- everything you've already done is saved exactly
    as you left it.</p>
    <p>If you have a question about where you are, or want to pick back up, the Certification
    Companion can help you find your place.</p>
    <p><a href="${companionUrl}">Open the Certification Companion</a></p>
    <p style="color:#888">If you'd rather not continue right now, you can ignore this -- we won't
    send another check-in about this for a while.</p>
  `.trim();
}

// ---------------------------------------------------------------------------
// Certification Operations Agent -- daily exception notification. Internal
// to admin/ops only, same posture as guideOperationsWaitingNotificationEmailHtml
// above: a mechanical fact about existing records, never an evaluation.
// ---------------------------------------------------------------------------
export function certificationOperationsExceptionEmailHtml({
  category,
  detail,
  derivedState,
  hostId,
  candidateId,
}: {
  category: string;
  detail: string;
  derivedState: string;
  hostId: string;
  candidateId: string;
}): string {
  return `
    <h2>Certification Operations: ${escapeHtml(category)}</h2>
    <p>${escapeHtml(detail)}</p>
    <p><strong>Operational state:</strong> ${escapeHtml(derivedState)}</p>
    <p><strong>Candidate ID:</strong> ${escapeHtml(candidateId)}</p>
    <p><strong>Host ID:</strong> ${escapeHtml(hostId)}</p>
    <p style="color:#888">This is a mechanical workflow notice only -- it does not evaluate
    competency, grade a Boundary Gate or Practicum, determine Critical Fail, or certify anyone.
    Review the candidate's record directly in /admin/guide-candidates to decide next steps.</p>
  `.trim();
}

// ---------------------------------------------------------------------------
// Guide Operations Agent -- daily access/mismatch notification. Internal to
// admin/ops only, same posture as certificationOperationsExceptionEmailHtml
// above: a mechanical fact about existing records, never a judgment, and
// never an automatic change to standing, role, or authorization.
// ---------------------------------------------------------------------------
export function guideAccessExceptionEmailHtml({
  mismatchType,
  detail,
  operationalState,
  hostId,
}: {
  mismatchType: string;
  detail: string;
  operationalState: string;
  hostId: string;
}): string {
  return `
    <h2>Guide Operations: ${escapeHtml(mismatchType)}</h2>
    <p>${escapeHtml(detail)}</p>
    <p><strong>Operational state:</strong> ${escapeHtml(operationalState)}</p>
    <p><strong>Host ID:</strong> ${escapeHtml(hostId)}</p>
    <p style="color:#888">This is a mechanical alignment notice only -- it does not decide
    certification, suspension, revocation, or authorization. Review the Guide's record directly
    in /admin/guide-operations to decide next steps.</p>
  `.trim();
}

// ---------------------------------------------------------------------------
// Host / Participant Operations Agent -- daily mismatch notification.
// Internal to admin/ops only, same posture as guideAccessExceptionEmailHtml
// above: a mechanical fact about existing records (never conversation
// content), never a judgment, and never an automatic change to
// membership_status, conversation/session status, or any access row.
// ---------------------------------------------------------------------------
export function hostParticipantOperationsExceptionEmailHtml({
  subjectType,
  category,
  detail,
  operationalState,
  subjectId,
}: {
  subjectType: "host" | "guide_participant";
  category: string;
  detail: string;
  operationalState: string;
  subjectId: string;
}): string {
  const subjectLabel = subjectType === "host" ? "Host" : "Guide-facilitated participant";
  return `
    <h2>Host / Participant Operations: ${escapeHtml(category)}</h2>
    <p>${escapeHtml(detail)}</p>
    <p><strong>Operational state:</strong> ${escapeHtml(operationalState)}</p>
    <p><strong>${escapeHtml(subjectLabel)} ID:</strong> ${escapeHtml(subjectId)}</p>
    <p style="color:#888">This is a mechanical alignment notice only -- it does not interpret what
    anyone meant, diagnose, prescribe, or decide institutional policy. Review the record directly
    in /admin/host-participant-operations to decide next steps.</p>
  `.trim();
}
