import type { VirtueFamilyKey } from "@/lib/virtues";
import { VIRTUES } from "@/lib/virtues";
import { STORY_LIBRARY } from "@/lib/chemistry-stories";

// Chemistry for Kids -- Printable Activity system.
//
// Four elements (the original pilot, below) have a hand-authored coloring
// scene and a bespoke puzzle tied to specific beats of their story. Every
// OTHER element that already has a completed story in
// lib/chemistry-stories.ts gets the same five-activity set automatically,
// generated by getActivitySet's fallback branch -- a generic decorative
// coloring page (the element's name, not a scene, since no bespoke
// illustration exists for it yet) and a generic maze puzzle labeled for
// that element. This is what lets the system scale to all 123 elements as
// their stories are written, without hand-building 123 one-off activity
// sets: only a bespoke scene/puzzle is optional, never required.
//
// Every activity is meant to be printed and used by hand -- colored,
// traced, drawn on, filled in. None of it is scored, graded, or used to
// assess a child's character. A child never needs to already "have" the
// element to do any of these; every activity works the same for every
// child, the same way every element is already available to everyone.
//
// Each element's five activities are designed to chain directly off its
// story: READ -> LISTEN -> WATCH (future animation) -> COLOR/CREATE -> NOTICE.

export type ActivityKind = "coloring" | "trace" | "draw-yourself" | "notice" | "puzzle";
export type AgeBand = "younger" | "older" | "both";
export type PuzzleKind = "matching" | "maze" | "sequence" | "card" | "maze-generic";

export type ActivityPageMeta = {
  id: string;
  kind: ActivityKind;
  title: string;
  ageBand: AgeBand;
  blurb: string;
};

export type ElementActivitySet = {
  elementSlug: string; // matches ChemistryStory.slug in lib/chemistry-stories.ts
  elementName: string;
  familyKey: VirtueFamilyKey;
  symbol: string;
  storyTitle: string;
  sceneCaption: string; // "" when there's no bespoke scene (generic fallback)
  puzzleTitle: string;
  puzzleKind: PuzzleKind;
  pages: ActivityPageMeta[];
};

function standardPages(elementName: string, puzzleTitle: string, hasScene: boolean): ActivityPageMeta[] {
  return [
    {
      id: "coloring",
      kind: "coloring",
      title: hasScene ? `Color the Story` : `Color the Word`,
      ageBand: "both",
      blurb: hasScene
        ? `A scene from ${elementName}'s story, ready to color in.`
        : `A decorative page built around ${elementName}, ready to color in.`,
    },
    {
      id: "trace",
      kind: "trace",
      title: `Trace & Color ${elementName}`,
      ageBand: "younger",
      blurb: `Big bubble letters to trace, then color in.`,
    },
    {
      id: "draw-yourself",
      kind: "draw-yourself",
      title: `Draw Yourself Using ${elementName}`,
      ageBand: "both",
      blurb: `A blank frame to draw a picture of yourself.`,
    },
    {
      id: "notice",
      kind: "notice",
      title: `Where Did You Notice ${elementName}?`,
      ageBand: "both",
      blurb: `Draw or write about where you saw it this week.`,
    },
    {
      id: "puzzle",
      kind: "puzzle",
      title: puzzleTitle,
      ageBand: "both",
      blurb: `A hands-on activity built around this element.`,
    },
  ];
}

export const ACTIVITY_PILOT: ElementActivitySet[] = [
  {
    elementSlug: "kindness-the-extra-seat",
    elementName: "Kindness",
    familyKey: "love",
    symbol: "Kd",
    storyTitle: "The Extra Seat",
    sceneCaption: "Mara made room at her table for Theo.",
    puzzleTitle: "Match the Kind Action",
    puzzleKind: "matching",
    pages: standardPages("Kindness", "Match the Kind Action", true),
  },
  {
    elementSlug: "courage-the-high-dive",
    elementName: "Courage",
    familyKey: "fortitude",
    symbol: "Cg",
    storyTitle: "The High Dive",
    sceneCaption: "Jonah stood at the edge of the high dive.",
    puzzleTitle: "Climb to the High Dive",
    puzzleKind: "maze",
    pages: standardPages("Courage", "Climb to the High Dive", true),
  },
  {
    elementSlug: "patience-the-slow-seed",
    elementName: "Patience",
    familyKey: "self-control",
    symbol: "Pn",
    storyTitle: "The Slow Seed",
    sceneCaption: "Oliver waited and watered his seed every day.",
    puzzleTitle: "Put the Seed's Growing in Order",
    puzzleKind: "sequence",
    pages: standardPages("Patience", "Put the Seed's Growing in Order", true),
  },
  {
    elementSlug: "appreciation-the-thank-you-note",
    elementName: "Appreciation",
    familyKey: "gratitude",
    symbol: "Ap",
    storyTitle: "The Thank-You Note",
    sceneCaption: "Sam handed the driver a thank-you card.",
    puzzleTitle: "Make Your Own Thank-You Card",
    puzzleKind: "card",
    pages: standardPages("Appreciation", "Make Your Own Thank-You Card", true),
  },
];

/** Any element with a completed story gets a full activity set -- a bespoke
 *  one for the original pilot four, a generic (but real, usable) one
 *  synthesized on the fly for every other element already in
 *  STORY_LIBRARY. Returns null only when the slug matches no story at all,
 *  since an activity set with nothing to connect back to isn't meaningful. */
export function getActivitySet(slug: string): ElementActivitySet | null {
  const bespoke = ACTIVITY_PILOT.find((a) => a.elementSlug === slug);
  if (bespoke) return bespoke;

  const story = STORY_LIBRARY.find((s) => s.slug === slug);
  if (!story) return null;
  const virtue = VIRTUES.find((v) => v.name === story.elementName);
  if (!virtue) return null;

  const puzzleTitle = `Find the Path to ${story.elementName}`;
  return {
    elementSlug: story.slug,
    elementName: story.elementName,
    familyKey: story.familyKey,
    symbol: virtue.symbol,
    storyTitle: story.title,
    sceneCaption: "",
    puzzleTitle,
    puzzleKind: "maze-generic",
    pages: standardPages(story.elementName, puzzleTitle, false),
  };
}

/** Every element that currently has a full printable activity set --
 *  the pilot four plus every other STORY_LIBRARY element, via the same
 *  fallback getActivitySet uses. Powers the activities index page without
 *  duplicating the "does this element qualify" logic. */
export function getAllActivitySets(): ElementActivitySet[] {
  return STORY_LIBRARY.map((s) => getActivitySet(s.slug)).filter(
    (a): a is ElementActivitySet => a !== null
  );
}
