import "server-only";
import type { SupabaseClient } from "@supabase/supabase-js";
import type { Stage } from "./engine/prompts";
import { STAGE_ORDER } from "./engine/conversation";

export const DEFYING_GRIEF_PROGRAM_NAME = "Defying Grief: A Sacred Rebellion";

// The real IAP custom GPT — the workshop. IAP is identical whether a
// conversation belongs to the general Journey or Defying Grief (Defying
// Grief's only content addition, DEFYING_GRIEF_CAT_AUDACITY, applies at CAT
// only), so the same GPT is reused rather than needing a second one.
export const IAP_GPT_URL =
  "https://chatgpt.com/g/g-6a2cc069e6688191b02bff51c3067c6a-individual-awareness-profile-iap-gpt";

// Display-only labels — the AI prompt itself still uses the official stage
// instructions (STAGE_LABEL in lib/engine/conversation.ts) untouched. Only
// what the participant sees on the Defying Grief dashboard changes.
export const DEFYING_GRIEF_STAGE_LABEL: Record<Stage, string> = {
  iap: "Individual Awareness Profile",
  cat: "Conversations Across Time: The Audacity of Grief",
  innercompass: "InnerCompass: The Audacity of Happiness",
};

const NOT_YET_AVAILABLE_COPY: Partial<Record<Stage, string>> = {
  cat: "Ready after your Individual Awareness Profile referral",
  innercompass: "Ready after your Conversations Across Time referral",
};

export type StageStatus = "complete" | "in-progress" | "not-yet-available";

export type DashboardStage = {
  stage: Stage;
  label: string;
  status: StageStatus;
  statusCopy: string;
  href: string | null;
};

export type DefyingGriefDashboard = {
  /** Whether this Host has begun Defying Grief at all. */
  started: boolean;
  stages: DashboardStage[];
  /** Room Identity — surfaced as-is from the participant's own referral
   *  content (roomIdentity from InnerCompass, or title from IAP/CAT while
   *  InnerCompass hasn't run yet). Never generated by this module. */
  roomIdentity: string | null;
  activeStage: Stage | null;
};

/** Reads existing conversations + referrals for this Host's Defying Grief
 *  conversations and derives dashboard state from them. Introduces no new
 *  continuity data — Room Identity and stage completion both come straight
 *  from referrals.content, keyed by the existing conversation_id link. */
export async function loadDefyingGriefDashboard(
  supabase: SupabaseClient,
  hostId: string
): Promise<DefyingGriefDashboard> {
  const { data: conversations } = await supabase
    .from("conversations")
    .select("id, stage, status")
    .eq("host_id", hostId)
    .eq("program", "defying-grief")
    .order("created_at", { ascending: true });

  const convos = conversations ?? [];

  if (convos.length === 0) {
    return {
      started: false,
      stages: STAGE_ORDER.map((stage) => ({
        stage,
        label: DEFYING_GRIEF_STAGE_LABEL[stage],
        status: "not-yet-available",
        statusCopy: stage === "iap" ? "Not yet available" : (NOT_YET_AVAILABLE_COPY[stage] ?? "Not yet available"),
        href: null,
      })),
      roomIdentity: null,
      activeStage: null,
    };
  }

  const conversationIds = convos.map((c) => c.id as string);
  const { data: referrals } = await supabase
    .from("referrals")
    .select("from_stage, content, created_at")
    .in("conversation_id", conversationIds)
    .order("created_at", { ascending: true });

  const allReferrals = referrals ?? [];
  const completedStages = new Set(allReferrals.map((r) => r.from_stage as Stage));
  const activeConvo = convos.find((c) => c.status === "active");
  const activeStage = (activeConvo?.stage as Stage) ?? null;

  const stages: DashboardStage[] = STAGE_ORDER.map((stage) => {
    const label = DEFYING_GRIEF_STAGE_LABEL[stage];
    if (completedStages.has(stage)) {
      return { stage, label, status: "complete", statusCopy: "Complete", href: "/workbook" };
    }
    if (activeStage === stage) {
      // IAP happens in the workshop (the real GPT), not on the website — a
      // Host returning to "Continue" IAP needs to go back to ChatGPT, not
      // to a website chat that has nothing in it.
      const href = stage === "iap" ? IAP_GPT_URL : "/journey";
      return { stage, label, status: "in-progress", statusCopy: "In progress", href };
    }
    return {
      stage,
      label,
      status: "not-yet-available",
      statusCopy: NOT_YET_AVAILABLE_COPY[stage] ?? "Not yet available",
      href: null,
    };
  });

  // Room Identity — read the most recent referral that carries it. InnerCompass
  // referrals carry `roomIdentity`; IAP/CAT referrals carry `title` (the same
  // continuity value under its earlier-stage name). Most recent wins so a
  // later, consciously-revised title supersedes an earlier one.
  let roomIdentity: string | null = null;
  for (let i = allReferrals.length - 1; i >= 0; i--) {
    const content = allReferrals[i].content as Record<string, unknown> | null;
    const value = (content?.roomIdentity ?? content?.title) as string | undefined;
    if (value) {
      roomIdentity = value;
      break;
    }
  }

  return { started: true, stages, roomIdentity, activeStage };
}

/** For the CAT-entry crossing screen only: the title IAP's referral produced,
 *  read the same way loadDefyingGriefDashboard reads Room Identity — no new
 *  storage, just a narrower read of the same data for a moment before the
 *  dashboard itself would normally show it. Returns null for any stage other
 *  than "cat" (the InnerCompass crossing screen doesn't show a title). */
export async function getIncomingRoomTitle(
  supabase: SupabaseClient,
  hostId: string,
  forStage: Stage
): Promise<string | null> {
  if (forStage !== "cat") return null;

  const { data: iapConvo } = await supabase
    .from("conversations")
    .select("id")
    .eq("host_id", hostId)
    .eq("program", "defying-grief")
    .eq("stage", "iap")
    .order("created_at", { ascending: false })
    .limit(1)
    .maybeSingle();
  if (!iapConvo) return null;

  const { data: referral } = await supabase
    .from("referrals")
    .select("content")
    .eq("conversation_id", iapConvo.id)
    .maybeSingle();
  const content = referral?.content as Record<string, unknown> | null;
  return (content?.title as string) ?? null;
}
