import "server-only";
import type { SupabaseClient } from "@supabase/supabase-js";
import { redirect } from "next/navigation";
import { createClient } from "@/lib/supabase/server";

// A parallel record to lib/engine/conversation.ts's DbConversation/DbMessage
// and lib/engine/unsung-heroes.ts's own pair, backed by
// unsaid_conversations/unsaid_messages -- kept fully separate so nothing
// here touches the core Journey's tables or Unsung Heroes' tables.

export type UnsaidMessage = {
  id: string;
  conversation_id: string;
  role: "host" | "guide";
  content: string;
  wants_response: boolean | null;
  created_at: string;
};

export type UnsaidConversation = {
  id: string;
  host_id: string;
  recipient: string;
  grounding: string | null;
  status: "active" | "complete";
  created_at: string;
  completed_at: string | null;
};

/** The opening line is a fixed, deterministic string -- never generated by
 *  a model call. It exists only to name the space, not to lead the Host. */
export function unsaidOpening(recipient: string): string {
  return `What still needs to be said to ${recipient}?`;
}

/** The Host's current active "What Still Needs to Be Said" conversation, if
 *  any (most recent). One active conversation at a time, same shape as
 *  Unsung Heroes -- starting a new one completes the current one first. */
export async function getActiveUnsaidConversation(
  supabase: SupabaseClient,
  hostId: string
): Promise<UnsaidConversation | null> {
  const { data } = await supabase
    .from("unsaid_conversations")
    .select("*")
    .eq("host_id", hostId)
    .eq("status", "active")
    .order("created_at", { ascending: false })
    .limit(1)
    .maybeSingle();
  return (data as UnsaidConversation) ?? null;
}

export async function createUnsaidConversation(
  supabase: SupabaseClient,
  hostId: string,
  recipient: string,
  grounding?: string | null
): Promise<UnsaidConversation> {
  const { data, error } = await supabase
    .from("unsaid_conversations")
    .insert({ host_id: hostId, recipient, grounding: grounding?.trim() || null })
    .select("*")
    .single();
  if (error) throw new Error(error.message);
  const convo = data as UnsaidConversation;

  await supabase.from("unsaid_messages").insert({
    conversation_id: convo.id,
    host_id: hostId,
    role: "guide",
    content: unsaidOpening(recipient),
    wants_response: null,
  });

  return convo;
}

export async function loadUnsaidMessages(
  supabase: SupabaseClient,
  conversationId: string
): Promise<UnsaidMessage[]> {
  const { data } = await supabase
    .from("unsaid_messages")
    .select("id, conversation_id, role, content, wants_response, created_at")
    .eq("conversation_id", conversationId)
    .order("created_at", { ascending: true });
  return (data as UnsaidMessage[]) ?? [];
}

/** Marks the current active conversation complete -- called only when the
 *  Host explicitly starts a new one. Nothing is deleted; it stays private
 *  and Host-owned, simply no longer the active thread. */
export async function completeUnsaidConversation(
  supabase: SupabaseClient,
  conversationId: string
): Promise<void> {
  await supabase
    .from("unsaid_conversations")
    .update({ status: "complete", completed_at: new Date().toISOString() })
    .eq("id", conversationId);
}

/** Placed here rather than as a page.tsx export for the same reason as
 *  startUnsungHeroesSession -- Next.js's App Router only allows a fixed set
 *  of named exports from a page.tsx. Completes any current active
 *  conversation (never deleted -- it stays privately accessible, just no
 *  longer the active thread) and starts a fresh one with the new
 *  recipient/grounding. */
export async function startUnsaidConversation(formData: FormData) {
  "use server";

  const supabase = createClient();
  const {
    data: { user },
  } = await supabase.auth.getUser();
  if (!user) redirect("/sign-in?from=/still-needs-to-be-said");

  const recipient = String(formData.get("recipient") ?? "").trim();
  if (!recipient) {
    redirect("/still-needs-to-be-said?error=" + encodeURIComponent("Who do you need to talk to?"));
  }
  const grounding = String(formData.get("grounding") ?? "").trim();

  const current = await getActiveUnsaidConversation(supabase, user.id);
  if (current) await completeUnsaidConversation(supabase, current.id);

  await createUnsaidConversation(supabase, user.id, recipient, grounding || null);
  redirect("/still-needs-to-be-said");
}

/** Ends the current active conversation without starting a new one --
 *  used by the "Start a new conversation" control to return the Host to
 *  the intake screen. The conversation itself is kept, just no longer
 *  active. */
export async function endUnsaidConversation(formData: FormData) {
  "use server";

  const supabase = createClient();
  const {
    data: { user },
  } = await supabase.auth.getUser();
  if (!user) redirect("/sign-in?from=/still-needs-to-be-said");

  const conversationId = String(formData.get("conversationId") ?? "").trim();
  if (conversationId) {
    await supabase
      .from("unsaid_conversations")
      .update({ status: "complete", completed_at: new Date().toISOString() })
      .eq("id", conversationId)
      .eq("host_id", user.id);
  }
  redirect("/still-needs-to-be-said");
}

/** The Host's explicit control over whether a conversation is kept -- the
 *  only way one of these is ever removed. Ownership-checked; deletes
 *  cascade to unsaid_messages via the foreign key. */
export async function deleteUnsaidConversation(formData: FormData) {
  "use server";

  const supabase = createClient();
  const {
    data: { user },
  } = await supabase.auth.getUser();
  if (!user) redirect("/sign-in?from=/still-needs-to-be-said");

  const conversationId = String(formData.get("conversationId") ?? "").trim();
  if (conversationId) {
    await supabase
      .from("unsaid_conversations")
      .delete()
      .eq("id", conversationId)
      .eq("host_id", user.id);
  }
  redirect("/still-needs-to-be-said");
}
