#!/bin/sh
# Generates lib/ops/expected-schema.generated.ts: what the running application
# EXPECTS the database to contain, derived mechanically from the code and the
# migrations so nobody has to remember to keep a list current.
#
#   tables   -> every table the application code reads or writes  (.from("x"))
#   rpcs     -> every database function the code calls            (.rpc("x"))
#   columns  -> every column the migrations ADD to an existing table
#
# Used by the production system checks (lib/ops/system-truth.ts) to notice, with
# no human involved, when code is deployed but the database is missing
# something it needs. This reads only source files and prints names: it never
# touches data.
#
# Usage:
#   sh scripts/expected-schema.sh           write the generated file
#   sh scripts/expected-schema.sh --check   exit 1 if the committed file is stale
#                                           (runs before every build, see package.json)
#
# POSIX sh + grep/sed/sort/awk only, so it behaves the same on a laptop and on
# the build machine.

set -eu

# Sorting and character classes must not depend on the machine's language
# settings, or the laptop and the build server would disagree about order.
LC_ALL=C
export LC_ALL

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
OUT="$ROOT/lib/ops/expected-schema.generated.ts"
TMP="$(mktemp)"
trap 'rm -f "$TMP" "$TMP.tables" "$TMP.rpcs" "$TMP.cols"' EXIT

cd "$ROOT"

# Table and function names the code actually uses.
grep -rhoE '\.from\("[a-z_][a-z0-9_]*"\)' app lib components --include='*.ts' --include='*.tsx' 2>/dev/null \
  | sed -E 's/\.from\("([a-z0-9_]+)"\)/\1/' | sort -u > "$TMP.tables"
grep -rhoE '\.rpc\("[a-z_][a-z0-9_]*"' app lib components --include='*.ts' --include='*.tsx' 2>/dev/null \
  | sed -E 's/\.rpc\("([a-z0-9_]+)"/\1/' | sort -u > "$TMP.rpcs"

# Columns the migrations add to existing tables: "table column" pairs.
# A statement is "alter table <name> ... add column [if not exists] <col> ..."
# (several add-column clauses may share one alter table). Comment lines are
# ignored; the current table is forgotten at each statement end (";").
cat supabase/migrations/*.sql 2>/dev/null | tr 'A-Z' 'a-z' | tr -d '\r' | awk '
  /^[ \t]*--/ { next }
  {
    line = $0
    if (match(line, /alter table (if exists )?(public\.)?[a-z_][a-z0-9_]*/)) {
      t = substr(line, RSTART, RLENGTH)
      sub(/^alter table (if exists )?(public\.)?/, "", t)
      cur = t
    }
    rest = line
    while (match(rest, /add column (if not exists )?[a-z_][a-z0-9_]*/)) {
      c = substr(rest, RSTART, RLENGTH)
      sub(/^add column (if not exists )?/, "", c)
      if (cur != "") print cur " " c
      rest = substr(rest, RSTART + RLENGTH)
    }
    if (line ~ /;[ \t]*$/) cur = ""
  }' | sort -u > "$TMP.cols"

{
  echo '// GENERATED by scripts/expected-schema.sh. Do not edit by hand.'
  echo '// Regenerate with:  sh scripts/expected-schema.sh'
  echo '// A build fails if this file is out of date (see "prebuild" in package.json).'
  echo
  echo '/** Every table the application code reads or writes. */'
  echo 'export const EXPECTED_TABLES: string[] = ['
  sed -E 's/^(.*)$/  "\1",/' "$TMP.tables"
  echo '];'
  echo
  echo '/** Every database function the application code calls. */'
  echo 'export const EXPECTED_RPCS: string[] = ['
  sed -E 's/^(.*)$/  "\1",/' "$TMP.rpcs"
  echo '];'
  echo
  echo '/** Columns the migrations add to existing tables, by table. */'
  echo 'export const EXPECTED_COLUMNS: Record<string, string[]> = {'
  awk '
    { if ($1 != prev) { if (prev != "") printf "],\n"; printf "  %s: [", $1; prev = $1; first = 1 }
      if (!first) printf ", "; printf "\"%s\"", $2; first = 0 }
    END { if (prev != "") printf "],\n" }' "$TMP.cols"
  echo '};'
} > "$TMP"

if [ "${1:-}" = "--check" ]; then
  if [ ! -f "$OUT" ]; then
    echo "expected-schema: $OUT is missing. Run:  sh scripts/expected-schema.sh" >&2
    exit 1
  fi
  if [ "$(tr -d '\r' < "$OUT")" != "$(cat "$TMP")" ]; then
    echo "expected-schema: lib/ops/expected-schema.generated.ts is out of date." >&2
    echo "The code or migrations now reference tables, functions or columns it does not list." >&2
    echo "Fix:  sh scripts/expected-schema.sh   (then commit the result)" >&2
    exit 1
  fi
  echo "expected-schema: up to date ($(wc -l < "$TMP.tables" | tr -d ' ') tables, $(wc -l < "$TMP.rpcs" | tr -d ' ') functions, $(wc -l < "$TMP.cols" | tr -d ' ') columns)."
else
  cp "$TMP" "$OUT"
  echo "expected-schema: wrote $OUT ($(wc -l < "$TMP.tables" | tr -d ' ') tables, $(wc -l < "$TMP.rpcs" | tr -d ' ') functions, $(wc -l < "$TMP.cols" | tr -d ' ') columns)."
fi
